export const metadata = {
  title: "My-App-Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightGreen",
            padding: "1rem",
            textAlign: "center",
          }}
        >
          <h1>Header</h1>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "darkblue",
            padding: "1rem",
            textAlign: "center",
          }}
        >
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  );
}
